spring:
  cloud:
    gateway:
      routes:
        - id: service_route
          uri: https://httpbin.org
          predicates:
            - Path=/service/**
          filters:
            - SetPath=/base64/Q2lzY28gU2VjdXJpdHkgQ2xvdWQgaXMgYXdlc29tZQ==
            #- Logging=Custom Filters Test Message, true, true
            - name: Logging
              args:
                baseMessage: Custom Filters Test Messages
                preLogger: true
                postLogger: true
            - name: ModifyRequest
              args:
                locale: en
            - name: CheckRequestHeaderAndAddResponseHeader
            - name: ModifyResponse
            #- ModifyRequest=en
        - id: request_rate_limiter
          uri: https://httpbin.org
          predicates:
            - Path=/redis/get/**
          filters:
            - SetPath=/base64/Q2lzY28gU2VjdXJpdHkgQ2xvdWQgaXMgYXdlc29tZQ==
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
